---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yolo-serving
commonLabels:
  component: yolo-serving
resources:
  - inferenceservice-yolov8.yaml
  - job-download-model-yolo.yaml
  - namespace.yaml
  - pvc-model-storage-yolo.yaml
  - servingruntime-triton.yaml
