apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-report-app-config
  labels:
    app: mobile-report-app
    component: mobile-report-app
data:
  YOLO_ENDPOINT: "https://yolo8m-predictor.user1.svc.cluster.local/v1"
