apiVersion: v1
kind: ConfigMap
metadata:
  name: mobile-report-app-config
  labels:
    app: mobile-report-app
    component: mobile-report-app
data:
  YOLO_ENDPOINT: "http://yolov8n-predictor.yolo-serving.svc.cluster.local:8000/v2/models/yolov8n/infer"
