apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-report-app
  labels:
    app: mobile-report-app
    component: mobile-report-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-report-app
  template:
    metadata:
      labels:
        app: mobile-report-app
        component: mobile-report-app
    spec:
      containers:
        - name: mobile-report-app
          image: image-registry.openshift-image-registry.svc:5000/mobile-report-app/mobile-report-app:latest
          imagePullPolicy: Always
          env:
            - name: MODEL_URL
              value: 'http://qwen3-vl-30b-a3b-instruct-fp8-predictor.vlm-serving.svc.cluster.local'
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
