apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mobile-report-app
commonLabels:
  component: mobile-report-app
resources:
  - namespace.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - s3-bucket.yaml
