apiVersion: v1
kind: Service
metadata:
  name: mobile-report-app
  labels:
    app: mobile-report-app
    component: mobile-report-app
spec:
  selector:
    app: mobile-report-app
  ports:
    - name: http
      port: 80
      targetPort: http
